blank_issues_enabled: false
contact_links:
  - name: Vnite 的 Telegram 群组 | Vnite's Telegram Server
    url: https://t.me/+d65-R_xRx1JlYWZh
    about: 问题有点抽象？为什么不问问万能的群友呢？ | Want to discuss / chat with the community? Here you go!