name: 交流建议 | Suggestion Make
title: "[Suggestion]: "
description: 对软件提些建议 | Make suggestion for the application
labels: "suggestion"
body:
  - type: textarea
    id: suggestion_description
    attributes:
      label: 建议内容
      description: 简单描述一下你想要的想法
    validations:
      required: true